import Image from "next/image";
import Head from "next/head";


export default function Home() {
    return (
        <>
            <Head>
                <title>Shamima Akter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="/dist/output.css" rel="stylesheet"></link>
            </Head>
            
            <div className="fixed -z-10 w-screen h-screen">
                <Image
                    src="/bgOne.jpg" 
                    alt="Mountains with snow"
                    layout="fill"
                    objectFit="cover" />
            </div>

            <div>
                <h1>hello</h1>
                <h1 class="text-3xl text-red-900 font-bold underline">Hello world!</h1>
                <h1 class="text-3xl text-rose-600 font-bold underline">Hello world!</h1>
                <h1 class="text-3xl text-sky-600 font-bold underline">Hello world!</h1>
            </div>
        </>
    );
}
